SUPABASE_URL=https://mfztenjrwtfjsgebmvda.supabase.co
SUPABASE_ANON_KEY=sb_publishable_goOnWdfw3tacBtKYBE7ZFA_JLhgM9vb
SMS_API_KEY=uk_aCh13hV8LlkN5l64mFXKQw1vn9ayYNZv4LNpmk5rzsp6f1Bzs8fUL2OGOJo1mL_5
SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1menRlbmpyd3RmanNnZWJtdmRhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MjcxOTgxMSwiZXhwIjoyMDk4Mjk1ODExfQ.Xs96smUK9DGSzDBrsehHaJKnYaSrDROJWMRnXVUM3jE
